### ISSUE TITLE
Cookie Plugin

### ISSUE THREAD

**Issue by kyleamadio** [DriveTimeInc/cordova-plugin-cookie-persistence#1]
Hi - thank you for doing this - have been pulling out my limited hair trying to get the server and session cookies to persist. I had determined that a Cordova Suspend was saving server cookies and a resume was returning them. Was about to try and figure out what it was doing...

**Comment by kyleamadio** [comment]
Hi  I have been testing the Cookie Persistence Plugin.

What I was hoping for can we save the Cookies when the user Closes the App, on Android, press the X or Close All or IOS double taps the Home button and swipes the app away?


![screenshot_20180315-215828](https://user-images.githubusercontent.com/1647986/37459429-1d4bdacc-289c-11e8-9079-9c870a0e4c43.png)

**Comment by gregberns** [comment]
@kyleamadio Hey glad you found it useful. Were still trying to figure out how to get it working in iOS, if you can help or know anyone it would help us get it working way faster.

On Android, from the testing we did, 'onPause' should be called anytime the app loses focus, so a home tap or the view to see all your apps.

Can you take a look at the logs and see if there's any information in them? The plugin is logging onPause, take a look for this in the logs: `CookiePersistenceCordovaPlugin  - Paused the activity.`
https://github.com/DriveTimeInc/cordova-plugin-cookie-persistence/blob/master/src/android/CookiePersistencePlugin.java#L52

**Comment by gregberns** [comment]
@kyleamadio Checkout PR #2. I forgot to remove some debugging code which caused cookies to be stored as an empty string.

**Comment by kyleamadio** [comment]
OK will update and see.

Also I was seeing the CookiePersistenceCordovaPlugin - Paused the activity message in the log -
