### ISSUE TITLE
Method to Cause Cookies to be Persisted

### ISSUE THREAD

**Issue by gregberns** [DriveTimeInc/cordova-plugin-cookie-persistence#6]
From @kyleamadio in #3 

If you can expose a method to call the storage logic from JS at anytime - we can then call the code to refresh the Cookies details whenever we make a HTTPs call to the server. That way we will not need to worry about Exit/Closing of the app as the developer can manage the cookie refresh as they are loaded from the the web server.

**Comment by gregberns** [comment]
Are you thinking a method like:

```
void storeCookies() {
  //retrieve cookies from view
  //store cookies in txt file
}
```

Or where the app would supply the cookies to store?

```
void storeCookies(cookies) {
  //store cookies in txt file
}
```

I'd think we'd want the first to maintain control.

Might also be worth adding a `clearCookies()` method that would wipe the persisted cookies.

**Comment by kyleamadio** [comment]
Let me test the updated Android code first - as I thought there are a technical issue with the exiting of the app. It may not be necessary (for Android) to interact with Javascript at all if the code works as expected....

**Comment by kyleamadio** [comment]
log data from Android simulator

V/FA: Session started, time: 854861
D/FA: Logging event (FE): session_start(_s), Bundle[{firebase_event_origin(_o)=auto, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=394842885034794583}]
V/FA: Connecting to remote service
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 1
V/FA: Inactivity, disconnecting from the service
D/CordovaActivity: Paused the activity.
W/com.facebook.appevents.AppEventsLogger: deactivateApp events are being logged automatically. There's no need to call deactivateApp, this is safe to remove.
D/CookiePersistenceCordovaPlugin: Paused the activity.
D/CookiePersistenceCordovaPlugin: Paused the activity.
**D/CookiePersistenceCordovaPlugin: Write File - Contents: magical_device=c2933b5e1d59497b881abfd9e7688421-18337; csrf_token=853407e979f440a4b130526f16f2999e-18337; magical=ee2242767a8f446eb29dbb292e606edf-18337; sess_user=c8bd3fc49baa0ae933bee23ea2a53f76-18337; magical_device=c2933b5e1d59497b881abfd9e7688421-18337; magicaltourstop=1; magical-friendProfileLikeCount=406
D/CookiePersistenceCordovaPlugin: storeCookies - Complete**
V/FA: Recording user engagement, ms: 19030
V/FA: Connecting to remote service
V/FA: Activity paused, time: 863894
D/FA: Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=19030, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=394842885034794583}]
V/FA: Connection attempt already in progress

      [ 03-16 08:47:26.675  1697: 2045 D/         ]
      HostConnection::get() New Host Connection established 0x83523940, tid 2045
D/EGL_emulation: eglMakeCurrent: 0xaa805fc0: ver 2 0 (tinfo 0xaa8038b0)
D/CordovaActivity: Stopped the activity.
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 2

**Comment by kyleamadio** [comment]
Perfect !

**Comment by kyleamadio** [comment]
Will test on a Samsung Galaxy S8 now

**Comment by gregberns** [comment]
That looks great. Yea its debatable whether this is needed.

**Comment by kyleamadio** [comment]
I have tested on my S8, the cookies do not seem to be getting passed to the web server - I have to login again. To test I clear all data, including the cookies and then start the app - login - then hardware show all apps. Close the app and start in again. Would expect to see the app in the logged in state. However asks for the login again. 

If I login again - the app behaves oddly and does not render data correctly. I'll get some info from the server logs and see what the application server received.

**Comment by gregberns** [comment]
Look for `Cookie File Content: <COOKIE STRING>` in the Android log. Also see if one of these exists: `UpdateCookies - Complete` or `UpdateCookies - Failed`

**Comment by kyleamadio** [comment]
The app serverr is receiving the cookies from the saved session - might be a bug in our code... checking.

One thing to consider - duplicate cookies. If the restart of the app add the same cookie - the developer will need to check for that in the JS code...

**Comment by kyleamadio** [comment]
another idea is have a option / config that indicates which cookies to store and re-store as it may not be appropriate to restore all the cookies on resume...

**Comment by kyleamadio** [comment]
Have done a set of tests and seems to be working correctly. I get another developer to do what I am doing. Start app, Login, Hardware Show all app, close app, restart the app from desktop.,,,

**Comment by gregberns** [comment]
I'm not opposed to it, but its a bit out of scope of my problem. If you want to take a stab and submit a PR to implement, that would be great.
> have a option / config that indicates which cookies to store and re-store
