### ISSUE TITLE
Duplicate Cookies - Different domain

### ISSUE THREAD

**Issue by kyleamadio** [DriveTimeInc/cordova-plugin-cookie-persistence#7]
Hi Greg - wonder if you are seeing this. we have a cookie 

magical  .dev.magic.al secure

If we kill the app - on start up we get two cookies, the duplicate drops the leading .

Its also random in that any one of our 5 or so cookies will duplicate.

magical  **.dev.magic.al** secure 

magical  **dev.magic.al**

**Comment by gregberns** [comment]
No sorry, I haven't seen that. It would be strange that a single character in the cookies string would be getting dropped.

**Comment by kyleamadio** [comment]
It is looking like it's an Android App backup issue. I'll try and get the
pattern clear and document it.

**Comment by kyleamadio** [comment]
Hi Greg - have been testing this  extensively and still think something odd happens with the cookies. we built versions of the app with and without the cookie persistence plugin and the one with the plugin would definitely duplicate a random single cookie. The code without the plugin code never duplicate.

**Comment by gregberns** [comment]
I'm more than willing to accept a PR if you can find a fix to the issue. For now I'll close the issue.
